### ISSUE TITLE
I'm getting an error when I try to run it.

### ISSUE THREAD

**Issue by aidenmitchell** [Code-Bullet/Pool_AI#4]
the error says 

No library found for shiffman.box2d
No library found for org.jbox2d.common
No library found for org.jbox2d.dynamics.joints
No library found for org.jbox2d.collision.shapes
No library found for org.jbox2d.collision.shapes
No library found for org.jbox2d.common
No library found for org.jbox2d.dynamics
No library found for org.jbox2d.dynamics.contacts
Libraries must be installed in a folder named 'libraries' inside the sketchbook folder (see the Preferences window)

**Comment by robinarthur** [comment]
You need this library for working.
https://github.com/shiffman/Box2D-for-Processing&ved=2ahUKEwjlmvfB18_aAhVDYJoKHaAzBokQFjAAegQIAhAB&usg=AOvVaw0K4TEwd_PlsETIJVcfomvj

**Comment by robinarthur** [comment]
Or even better, try to download it with the library manager in the processing editor

**Comment by HyPeReloaded** [comment]
The link you posted is broken, can you post a working one please?

**Comment by robinarthur** [comment]
- open your processing editor
- click on "Tools" in the Menu
- "Add Tool..."
- click on the "Libraries" Tab and search for the BOX2D Package

after you installed it, it should run...

**Comment by HyPeReloaded** [comment]
Thanks! It worked
